---
collections:
  photos:
    output: false

defaults:
  - scope:
      path: ""
      type: photos
    values:
      layout: photo

plugins: [jekyll-paginate]

highlight: rouge
markdown: kramdown
name: isaacschultz
url: "https://www.isaacschultz.com"
paginate: 3
