--- 
collections: 
  photos: 
    output: true

defaults:
  - scope:
      path: ""
      type: photos
    values:
      layout: photo
    permalink: /gallery/index.html

gems: [jekyll-paginate]

highlight: pygments
markdown: kramdown
name: isaacschultz
url: "https://www.isaacschultz.com"
paginate: 3
